version: '3'
services:

  database:
    image: postgres:alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.prod.db
    restart: always

  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    links:
      - database

  app:
    build:
      context: .
    expose:
      - 8000
    volumes:
      - ./djblog/static:/djblog/static
    env_file:
      - .env.prod
    restart: always
    command: gunicorn djblog.wsgi --bind 0.0.0.0:8000
    links:
      - database
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ./djblog/static:/var/www/static
    links:
      - app
    ports:
      - 80:8989