version: '3'
services:

  database:
    image: postgres:alpine
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_DB=djblog
      - POSTGRES_USER=djblog
      - POSTGRES_PASSWORD=djblog
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  redis:
    image: redis:alpine
    hostname: redis
    restart: always
    links:
      - database

  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djblog:/djblog
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=djblog
      - DB_USER=djblog
      - DB_PASS=djblog
      - APP_DEBUG=1
      - APP_SECRET_KEY=very_secret_key
      - APP_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    links:
      - database
      - redis