name: Publish

on:
  push:
    tags: 
     - v[1-9]+.[0-9]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: zip -r djblog_${{ github.ref_name }}.zip app
      
      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "djblog_${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}