name: Tests

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Start docker-compose
      working-directory: ./app
      run: docker-compose -f docker-compose.yml up -d

    - name: Run tests
      working-directory: ./app
      run: docker-compose run --rm app sh -c "python manage.py test blog.tests"